### ISSUE TITLE
Completion/Snippet expansion does not happen when you hit <TAB>

### ISSUE THREAD

**Issue by s-daveb** [prabirshrestha/asyncomplete-ultisnips.vim#5]
When i register this as a completion source and try to select a snippet and hit `<enter>,` nothing happens.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/2100425/69636450-a1583100-1024-11ea-8d5b-d2fa9600661d.png">

my .vimrc contains

```

let g:asyncomplete_auto_popup = 1
let g:asyncomplete_remove_duplicates = 1
let g:lsp_async_completion = 1

"  Enable disagnostics
let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1

" [...] other language servers

if has('python3')
    let g:UltiSnipsExpandTrigger="<c-l>"
    "let g:UltiSnipsExpandTrigger="<c-y>"
    call asyncomplete#register_source(asyncomplete#sources#ultisnips#get_source_options({
        \ 'name': 'ultisnips',
        \ 'whitelist': ['*'],
        \ 'completor': function('asyncomplete#sources#ultisnips#completor'),
        \ }))
endif

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"

nnoremap <buffer> ,n :LspNextError<CR>
nnoremap <buffer> ,p :LspPreviousError<CR>imap <m-r> <Plug>(asyncomplete_force_refresh)

set completeopt=menu,menuone,preview,noinsert
```

Is this plug-in deprecated?

The documentation for asyc.vim says to use this repository for snippets, and the documentation for vim-lsp.vim says to use thomasfaingnaert/vim-lsp-ultisnips.

**Comment by Pedrobc89** [comment]
Probably because of this line: `let g:UltiSnipsExpandTrigger="<c-l>"`

**Comment by s-daveb** [comment]
@Pedrobc89 I can see how you would say that, but that was my workaround to get UltiSnip functionality while &lt;TAB&gt;wasn't working.  I should have removed that before filing this bug report.

In either case, I tested it again with the latest versions of all my plugins, and the UltiSnips provider is working with &lt;TAB&gt; again. 🥳 

Marking this as closed/solved.

**Comment by dezza** [comment]
Hey man, just wanted to chime in if anyone is in a similar situation.

I think the takeaway from this issue is that this plugin only populates sources (completion results), _(please correct me if I'm wrong)_

You can achieve snippet expansion from menu by:
```vim
" vim8/legacy
function! ExpandSnippetOrReturn()
  let snippet = UltiSnips#ExpandSnippetOrJump()
  if g:ulti_expand_or_jump_res > 0
    return snippet
  else
    return "\<C-Y>" " select without newline in popup
  endif
endfunction

inoremap <expr> <CR> pumvisible() ? "<C-R>=ExpandSnippetOrReturn()<CR>" : "\<CR>"
```

```vim
vim9script
def g:ExpandSnippetOrReturn(): string
  var snippet = UltiSnips#ExpandSnippetOrJump()
  if g:ulti_expand_or_jump_res > 0
    return snippet
  else
    return "\<C-Y>" # select without newline in popup
  endif
enddef

inoremap <expr> <CR> pumvisible() ? "<C-R>=ExpandSnippetOrReturn()<CR>" : "\<CR>"
```
